# Generated by Django 5.1.4 on 2025-01-12 01:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='languages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=50, unique=True)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=25, unique=True)),
                ('Lastname', models.CharField(max_length=25, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Date_of_birth', models.DateField()),
                ('Git_address', models.URLField(unique=True)),
                ('linkedin_address', models.URLField(unique=True)),
                ('Phone', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('photo', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='assign_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.languages')),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('project_link', models.URLField(unique=True)),
                ('description', models.TextField()),
                ('project_language', models.ManyToManyField(through='myapp.assign_language', to='myapp.languages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='myapp.users')),
            ],
        ),
        migrations.AddField(
            model_name='assign_language',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projects'),
        ),
    ]
